package bootstrap

import (
	"errors"
	"fmt"
	"github.com/senseyedeveloper/pereza/parser"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Generator struct {
	parser   *parser.Parser
	settings Settings
}

func NewGenerator(parser *parser.Parser, settings Settings) *Generator {
	return &Generator{parser: parser, settings: settings}
}

func (g *Generator) Run() error {
	for _, filename := range g.settings.Filenames {
		err := g.generate(filename)

		if err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) generate(filename string) error {
	fileInfo, err := os.Stat(filename)
	if err != nil {
		return err
	}

	result, err := g.parser.Parse(filename, fileInfo.IsDir())
	if err != nil {
		return err
	}

	const suffix = "_perezajson.go"

	var outName string
	if fileInfo.IsDir() {
		outName = filepath.Join(filename, result.PackageName+suffix)
	} else {
		s := strings.TrimSuffix(filename, ".go")

		// FIXME: up before parse
		if s == filename {
			return errors.New("filename must end in '.go'")
		}

		outName = s + suffix
	}

	fmt.Printf("source filename %s\n"+
		"parser result %+v\n"+
		"output filename %s\n", filename, result, outName)

	return g.output(outName, result)
}

func (g *Generator) output(outName string, result parser.Result) error {
	f, err := os.Create(outName)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// TEMPORARY AUTOGENERATED FILE: perezajson stub code to make the package")
	fmt.Fprintln(f, "// compilable during generation.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package ", result.PackageName)

	types := result.StructNames
	sort.Strings(types)
	for _, t := range types {
		fmt.Fprintln(f)
		fmt.Fprintln(f, "func (", t, ") MarshalJSON() ([]byte, error) { return nil, nil }")
		fmt.Fprintln(f, "func (*", t, ") UnmarshalJSON([]byte) error { return nil }")
	}

	return nil
}
