language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

script:
  - make test

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep