// Code generated by pereza for marshaling/unmarshaling. DO NOT EDIT.

package bson

// MarshalBSON supports bson.Marshaler interface
func (PerezaEmptyState) MarshalBSON() ([]byte, error) {
	return []byte{0x05, 0x0, 0x0, 0x0, 0x0}, nil
}
