// TEMPORARY AUTOGENERATED FILE: perezajson stub code to make the package
// compilable during generation.

package fixtures

func (PerezaDoubleBoolState) MarshalJSON() ([]byte, error) { return nil, nil }
func (*PerezaDoubleBoolState) UnmarshalJSON([]byte) error  { return nil }

type PerezaJSON_exporter_PerezaDoubleBoolState *PerezaDoubleBoolState
