// Code generated by pereza for marshaling/unmarshaling. DO NOT EDIT.

package boolean

// MarshalBSON supports bson.Marshaler interface
func (v PerezaBoolState) MarshalBSON() ([]byte, error) {
	if v.State {
		return []byte("\x0d\x00\x00\x00\x08state\x00\x01\x00"), nil
	}

	return []byte("\x0d\x00\x00\x00\x08state\x00\x00\x00"), nil
}
